### ISSUE TITLE
Fix for scriptcs 0.15.0

### ISSUE THREAD

**Issue by adamralph** [scriptcs-contrib/scriptcs-webapi#20]
Currently the script pack insists an a `Common.Logging.ILog` being injected but in scriptcs 0.15 we do not, and cannot, register that type in the container, since then the container will not be able to pick a constructor for various types which have both a `Common.Logging.ILog` overload and a `ScriptCs.Contracts.ILogProvider` overload.

After the scriptcs 0.15.0 release, the script pack should be upgraded to the 0.15.0 binaries and insist on a `ScriptCs.Contracts.ILogProvider` being injected instead.

**Comment by tmedanovic** [comment]
@adamralph  Are there any plans to fix this some time soon?

**Comment by adamralph** [comment]
@tmedanovic I see you've gone ahead and fixed it :+1: 

Now you just have to persuade @glennblock to release it :wink:
